// flow-typed signature: fb16168063e36b5a90100fe97e9bb061
// flow-typed version: <<STUB>>/mdbreact_v^4.27.0/flow_v0.136.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mdbreact'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mdbreact' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mdbreact/dist/mdbreact.esm' {
  declare module.exports: any;
}

declare module 'mdbreact/dist/mdbreact' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mdbreact/dist/mdbreact.esm.js' {
  declare module.exports: $Exports<'mdbreact/dist/mdbreact.esm'>;
}
declare module 'mdbreact/dist/mdbreact.js' {
  declare module.exports: $Exports<'mdbreact/dist/mdbreact'>;
}
