// flow-typed signature: d9074d7d435c5bdf1476a565899aff6f
// flow-typed version: <<STUB>>/@csstools/normalize.css_v^11.0.1/flow_v0.136.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@csstools/normalize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@csstools/normalize.css' {
  declare module.exports: any;
}
